version: "3"

services:
  email:
    container_name: status_email
    image: overshard/exim
    restart: unless-stopped
  web:
    container_name: status_web
    build: .
    env_file: .env
    volumes:
      - /srv/data/status/:/data/
    ports:
      - "${PORT}:${PORT}"
    command: >
      gunicorn status.asgi:application --preload --workers 2 --max-requests 256
      --timeout 30 --bind :${PORT} --worker-class uvicorn.workers.UvicornWorker
      --error-logfile - --access-logfile -
    restart: unless-stopped
  worker:
    container_name: status_worker
    build: .
    env_file: .env
    volumes:
      - /srv/data/status/:/data/
    command: >
      python3 manage.py scheduler
    restart: unless-stopped
