version: "3"

services:
  web:
    container_name: status_web
    build: .
    env_file: .env
    volumes:
      - /srv/data/status/:/data/
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    command: ./entrypoint.py
    restart: unless-stopped
    init: true
