# A docker compose file to run an status server
#
# We need to make sure the db.sqlite3 database is stored on the host machine
# to maintain the data across rebuilds.

version: "3"

services:
  web:
    container_name: status_web
    build: .
    env_file: .env
    volumes:
      - /srv/data/status/media/:/data/media/
    ports:
      - "${PORT}:${PORT}"
    command: >
      sh -c "python3 manage.py scheduler &
             gunicorn status.asgi:application --worker-class uvicorn.workers.UvicornWorker
             --workers 4 --bind :${PORT} --log-file - --access-logfile - --error-logfile -"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.3-alpine
    container_name: status_db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /srv/data/status/db/:/var/lib/postgresql/data/
    restart: unless-stopped
