# Generated by Django 4.0.5 on 2022-06-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
