# Generated by Django 4.0.6 on 2022-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_last_lighthouse_run_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['url'], name='properties__url_7229e0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['user'], name='properties__user_id_c32bda_idx'),
        ),
    ]
