# Generated by Django 4.0.6 on 2022-07-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_properties__url_7229e0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='run_interval',
        ),
    ]
