# Generated by Django 4.0.6 on 2022-07-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_run_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_run_at_crawler',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='next_run_at_crawler',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
