# Generated by Django 4.0.6 on 2022-07-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_last_run_at_crawler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='crawler_insights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
