# Generated by Django 4.1 on 2025-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_crawler_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="alert_state",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down")], default="up", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="last_alert_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
