# Generated by Django 6.0.4 on 2026-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_lighthouse_error_tracking"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="check",
            index=models.Index(
                fields=["property", "-created_at"],
                name="properties__propert_b3e3ac_idx",
            ),
        ),
    ]
