# Generated by Django 6.0.4 on 2026-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_check_properties__propert_b3e3ac_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="crawl_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="crawl_state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="last_crawl_duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="last_crawl_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="last_crawl_pages_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="last_crawl_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="last_lighthouse_duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="lighthouse_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="lighthouse_state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
    ]
