# Generated by Django 6.0.4 on 2026-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_crawl_lighthouse_state_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="lighthouse_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
